RegionalDR example application
RHEcosystemAppEng/regional-resiliency-pattern pull request #7
Opened 2024-04-01 15:02 UTC by r2dedios

Included Doc and Manifests for deploying a test application for checking the RegionalDR

2024-04-03 21:42 UTC, TomerFi requested changes

2024-04-03 21:42 UTC, TomerFi commented on README.md
> +- [Deploy an example DR Application](./rdr-example-app/README.md)
Revert this to `[example-app]` and scroll down to the end of the README; there, you will find the link that needs to be modified.

![image](https://github.com/RHEcosystemAppEng/regional-resiliency-pattern/assets/28388442/a36c8e41-e931-49e8-abea-5665e81dec92)

2024-04-03 21:51 UTC, TomerFi commented
@r2dedios We don't need both example apps. We should delete the old _busybox_ one while PRing the new _pacman_ one.

Also, the previous example app folder structure was:
- [doc/](https://github.com/r2dedios/regional-resiliency-pattern/blob/pattern-final-fixes/doc/) - All documentation-related, i.e. images and markdowns.
- [doc/ExampleDRApp.md](https://github.com/r2dedios/regional-resiliency-pattern/blob/pattern-final-fixes/doc/ExampleDRApp.md) - The example app documenation.
- [doc/example-app](https://github.com/r2dedios/regional-resiliency-pattern/tree/pattern-final-fixes/doc/example-app) - The example app manifests.

The new example app diverged from this structure and was placed in the project's root. Should we adapt to the previous structure to be consistent with the rest of the pattern documentation?

2024-04-03 21:54 UTC, TomerFi commented
For the failing markdown lint, you can run this locally to work through the errors:

```shell
podman run --privileged \
  -e RUN_LOCAL=true \
  -e DEFAULT_BRANCH=main \
  -e VALIDATE_MARKDOWN=true  \
  -e VALIDATE_NATURAL_LANGUAGE=true  \
  -v $PWD:/tmp/lint \
  ghcr.io/super-linter/super-linter:latest
```

2024-04-03 21:59 UTC, TomerFi commented
@r2dedios I just noticed you created this PR from the branch `pattern-final-fixes,` which was already merged here: https://github.com/RHEcosystemAppEng/regional-resiliency-pattern/pull/5. (That explains 107 commits...).
![image](https://github.com/RHEcosystemAppEng/regional-resiliency-pattern/assets/28388442/12cf7452-7bd9-4da9-b147-33ed991ec425)

You should refresh your fork, create a new branch from the main one, and only include commits relevant to this PR.

2024-04-10 16:49 UTC, r2dedios commented
PR wrong created

2024-04-10 16:49 UTC, closed without merging